# Generated by Django 4.1.2 on 2022-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=200)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('n', 'New'), ('r', 'Rendered'), ('p', 'Printed')], default='n', max_length=1)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.printer')),
            ],
        ),
    ]
